services:
  postgres:
    image: postgres:16
    container_name: crm-db
    environment:
      POSTGRES_DB: bank_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"