spring:
  application:
    name: bank-crm
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_crm
    username: postgres
    password: password
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
